src/Microsoft.Restier.EntityFramework/Microsoft.Restier.EntityFramework.csproj, src/Microsoft.Restier.EntityFramework/Model/ModelMapper.cs, src/Shared/TypeExtensions.cs
Currently, restier does not support IDbSet<> implementations other than DbSet<>. So, if one implements a custom IDbSet<> implementation, or even extends the default implementation, DbSet<>, he/she would not be able to use it with RESTier. Because, as far as i know by inspecting the ModelMapper implementation, any IDbSet<> implementation not being DbSet<> is rejected.
For example, when using IdentityDbContext, because it defines the entity sets as IDbSet<>, i have not be able to work it with Restier.
To overcome this problem, i created my custom IModelMapper by just copying the default one, and adding the changes i included in this commit. Currently i am using this implementation and I don't know if there is any reason for this constraint in the default implementation. So, instead of …
=> Supporting any IDbSet<> implementations

src/Microsoft.Restier.EntityFramework7/Submit/ChangeSetPreparer.cs
EF7 ChangeSetPreparer.PrepareAsync is using the wrong ApiContext.GetProperty name to find the current DbContext. It is currently hard-coded to "DbContext", when it should be using the DbApiConstants.DbContextKey constant.
This causes a NullReferenceException during change set submission because it can't find the dbContext.
=> EF7 ChangeSetPreparer.PrepareAsync is using the wrong ApiContext Property

src/Microsoft.Restier.Core/ApiBuilder.cs, src/Microsoft.Restier.Core/ApiBuilderExtensions.cs, src/Microsoft.Restier.Core/ApiConfiguration.cs, src/Microsoft.Restier.Core/ApiContext.cs, src/Microsoft.Restier.Core/IApiScopeFactory.cs, src/Microsoft.Restier.Core/Microsoft.Restier.Core.csproj, src/Microsoft.Restier.Core/packages.config, test/Microsoft.Restier.TestCommon/PublicApi.bsl
1. The digital signature of DI 1.0.0-beta8 is expired since 2/1/2016 which will fail strong name validation.
2. The TFS build machine is still using VS2013 so we have to remove the C# 6.0 language features in order to compile.
=> Fix TFS build break

src/Microsoft.Restier.WebApi/RestierController.cs, src/Microsoft.Restier.WebApi/RestierQueryBuilder.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/E2ETestBase.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/Microsoft.Restier.WebApi.Test.Scenario.csproj, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/PropertyAccessTests.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinE2ETestCases.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinInMemoryE2ETest.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Models/Person.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Models/TrippinModel.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.TrippinInMemory/Models/Person.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.TrippinInMemory/Models/TrippinApi.cs
This is for issue #305 
Issue found: 
1. Incorrect path like collection/$valuewill return 404 but not 400 (badrequest), this is handled by WebApi
2. Null single value will return 200 but not 204
3. Null complex and request complex property will have 500 (NullReferenceException )
4. Null single navigation request will return 500
Issues which are not fixed yet
1. Incorrect path like collection/$value will return 404 but not 400 (badrequest), this is handled by WebApi. Tracked with OData/WebApi#683
2. Request single navigation property with null value return 404 now as cannot differentiate ~/People(nonexistkey) (404) vs /People(5)/NullSingNav (204) now. Tracked with Issue #288
3. Request with non-existing entity's prop will return 204 /200, should be 404. Tracked with Issue #328 
4. Null …
=> Add test case for null case and fix issues found

src/Microsoft.Restier.WebApi/RestierController.cs, src/Microsoft.Restier.WebApi/RestierQueryBuilder.cs, test/Microsoft.Restier.Samples.Northwind.Tests/Microsoft.Restier.Samples.Northwind.Tests.csproj, test/Microsoft.Restier.Samples.Northwind.Tests/packages.config, test/Microsoft.Restier.TestCommon/Microsoft.Restier.TestCommon.csproj, test/Microsoft.Restier.TestCommon/packages.config, test/Microsoft.Restier.WebApi.Test/Microsoft.Restier.WebApi.Test.csproj, test/Microsoft.Restier.WebApi.Test/packages.config, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinInMemoryE2ETest.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.TrippinInMemory/Models/TrippinApi.cs
Partially fix issue of #330 , will return empty collection when collection is null on server side for primitive type/enum/complex,  and nav property collection is not fixed as EF does not support to have collection!=null in LINQ.
=> Make null collection of primitive/enum/complex return correct code

src/GlobalSuppressions.cs, src/Microsoft.Restier.Core/Properties/Resources.Designer.cs, src/Microsoft.Restier.Core/Properties/Resources.resx, src/Microsoft.Restier.Core/Submit/ChangeSet.cs, src/Microsoft.Restier.Core/Submit/DefaultSubmitHandler.cs, src/Microsoft.Restier.WebApi/HttpConfigurationExtensions.cs, src/Microsoft.Restier.WebApi/Microsoft.Restier.WebApi.csproj, src/Microsoft.Restier.WebApi/Query/RestierQueryExecutor.cs, src/Microsoft.Restier.WebApi/Query/RestierQueryExecutorOptions.cs, src/Microsoft.Restier.WebApi/RestierController.cs, test/Microsoft.Restier.TestCommon/PublicApi.bsl
This PR fixes #321.
We are removing `ChangeSetAnEntityHasChanged` and the related logic in `DefaultSubmitHandler` because:
- The current concurrency logic in `DefaultSubmitHandler` is hard to read and vulnerable. How do we determine the inner loop count and the outer loop count exactly?
- Currently there is no concurrency between changeset addition and changeset submission according to the implementation of `RestierChangeSetProperty`. If we do have this need, we can have a more robust design later.
- For now, the simplest code offers the best performance.
=> Remove ChangeSet.AnEntityHasChanged and related logic

src/Microsoft.Restier.WebApi/RestierController.cs, src/Microsoft.Restier.WebApi/ServiceCollectionExtensions.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/UrlConventionsTests.cs, test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Api/TrippinApi.cs
*This pull request fixes issue #359 .*  
Make ODataQuerySetting and ODataValicationSetting as DI service so user can customize the settings.
Document is needed.
=> Allow to customized OData query and validation setting.

README.md, src/GlobalSuppressions.cs, src/Microsoft.Restier.WebApi/Formatter/Deserialization/DefaultRestierDeserializerProvider.cs, src/Microsoft.Restier.WebApi/Formatter/Deserialization/RestierDeserializerProviderProxy.cs, src/Microsoft.Restier.WebApi/Formatter/RestierFormattingAttribute.cs, src/Microsoft.Restier.WebApi/Formatter/Serialization/DefaultRestierSerializerProvider.cs, src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierSerializerProviderProxy.cs, src/Microsoft.Restier.WebApi/HttpRequestMessageExtensions.cs, src/Microsoft.Restier.WebApi/Microsoft.Restier.WebApi.csproj, src/Microsoft.Restier.WebApi/RestierController.cs, src/Microsoft.Restier.WebApi/Routing/RestierRoutingConvention.cs, src/Microsoft.Restier.WebApi/ServiceCollectionExtensions.cs, test/Microsoft.Restier.TestCommon/PublicApi.bsl, test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.Tests/ODataFeedTests.cs, test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.Tests/OperationTests.cs, test/Shared/ODataTestHelpers.cs
*This pull request fixes issue #301.*  
Make serializer and deserializer provider as DI service, and only works for RESTier controller.
In case of error or user defined controller, default provider will be used.
Document is needed.
=> Allow serializer provider can be customized with DI services

BuildNuGets.cmd
Project file name changed from WebApi to OData.  This file had the old project filename.
- [  ] Test cases added
=> Update wrong project filename

src/Microsoft.Restier.Providers.EntityFramework7/Submit/ChangeSetInitializer.cs, test/Microsoft.Restier.Providers.EntityFramework7.Tests/DateTests.cs, test/Microsoft.Restier.Providers.EntityFramework7.Tests/Models/Primitives/PrimitivesApi.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Northwind.EF7.Tests/Microsoft.OData.Service.Sample.Northwind.EF7.Tests.csproj, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Northwind/Models/NorthwindContext.cs
- EFCore RC2 supports quite a few annotations now, remove unnecessary configuration code in samples.
- Add derived type support to EFCore submit pipeline.
There're 5 UT failures in Sample.Tests, I believe not related to this change.
=> Remove unnecessary EFCore configuration code in sample projects.

src/Microsoft.Restier.Publishers.OData/Routing/HttpConfigurationExtensions.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/UrlConventionsTests.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Api/TrippinApi.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Extension/CustomizedSubmitProcessor.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Extension/PathAndSlashEscapeODataPathHandler.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Microsoft.OData.Service.Sample.Trippin.csproj, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Models/TrippinModel.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Web.config
*This pull request fixes issue #415 and it is a temp solution for #414 
Make URL can parse slash or backslash in key of entity
This is a temp solution, need to revisit when key as alias is supported by ODL, and this is tracked with https://github.com/OData/RESTier/issues/421
=> Temp solution for URI with backslash and slash

src/Microsoft.Restier.Publishers.OData/Model/RestierModelBuilder.cs, src/Microsoft.Restier.Publishers.OData/Routing/HttpConfigurationExtensions.cs
*This pull request fixes issue #432 .*  
If we use call api.GetModelAsync().Result, then the exception been thrown is wrapped and only inner exception has meaningful message.
If we change to await api.GetModelAsync(), then the exception been thrown will not be wrapped and the exception is meaningful.
=> Improve model built exception been thrown

src/GlobalSuppressions.cs, src/Microsoft.Restier.Core/Model/ModelContext.cs, src/Microsoft.Restier.Providers.EntityFramework/Model/ModelProducer.cs, src/Microsoft.Restier.Publishers.OData/Model/RestierModelBuilder.cs, test/Microsoft.Restier.Publishers.OData.Test/Microsoft.Restier.Publishers.OData.Test.csproj, test/Microsoft.Restier.Publishers.OData.Test/app.config, test/Microsoft.Restier.Publishers.OData.Test/packages.config, test/Microsoft.Restier.TestCommon/PublicApi.bsl, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Northwind.Tests/Baselines/TestGetNorthwindMetadata.txt, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Northwind/Models/NorthwindApi.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Models/Airline.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Models/TrippinModel.cs
*This pull request fixes issue #413 .*  
In Restier 0.5, the model building uses Web APi OData conversion model builder which finds keys of entity type based on ,
a. Whether there is any proeprty marked with key attribute.
b. Whether there is property with name ID or entitytypeNameID
But if the entity type does not define key in this way, then model build will fail
This issue retrieves keys from entity framework and set to model builder.
=> Make model auto pop keys from Entity framework.

src/Microsoft.Restier.Core/Submit/ChangeSetItem.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinE2EEtagTestCases.cs
*This pull request fixes issue #491.*  
Byte array cannot be used to check ETag, and now it's OK.
=> Fix issue #491

test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinInMemoryE2ETest.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/Models/Person.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/Models/TripPinDataSource.cs
Remove AutoExpand attribute of Friends, change Trips to be not null to avoid WebApi query to throw ArgumentNullException.
=> Remove AutoExpand attribute of Friends, change Trips to be not null.

README.md, src/Microsoft.Restier.Core/ApiBaseExtensions.cs, src/Microsoft.Restier.Core/Model/IModelMapper.cs, src/Microsoft.Restier.Providers.EntityFramework/Model/ModelMapper.cs, src/Microsoft.Restier.Providers.EntityFramework/Model/ModelProducer.cs, src/Microsoft.Restier.Providers.EntityFramework/Submit/ChangeSetInitializer.cs, src/Microsoft.Restier.Publishers.OData/Extensions.cs, src/Microsoft.Restier.Publishers.OData/Model/EdmHelpers.cs, src/Microsoft.Restier.Publishers.OData/Model/ModelMapper.cs, src/Microsoft.Restier.Publishers.OData/Model/RestierModelExtender.cs, src/Microsoft.Restier.Publishers.OData/Operation/OperationExecutor.cs, src/Microsoft.Restier.Publishers.OData/Query/RestierQueryBuilder.cs, src/Microsoft.Restier.Publishers.OData/Query/RestierQueryExecutor.cs, src/Microsoft.Restier.Publishers.OData/RestierController.cs, src/Microsoft.Restier.Publishers.OData/Routing/HttpConfigurationExtensions.cs, test/Microsoft.Restier.Core.Tests/Api.Tests.cs, test/Microsoft.Restier.Publishers.OData.Test/FallbackTests.cs, test/Microsoft.Restier.Publishers.OData.Test/StoreApi.cs, test/Microsoft.Restier.TestCommon/PublicApi.bsl
related to PR https://github.com/OData/RESTier/pull/502
=> Make some APi public to facilitate some advance use case

src/Microsoft.Restier.Providers.EntityFramework/Submit/ChangeSetInitializer.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/E2ETestBase.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/Microsoft.OData.Service.Sample.Tests.csproj, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinE2ETestCases.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinInMemoryE2ETest.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/packages.config, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Models/OrderDetail.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Models/TrippinModel.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/App_Start/WebApiConfig.cs, test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/Web.config, test/ODataEndToEnd/Microsoft.Restier.Providers.InMemory/Submit/ChangeSetInitializer.cs
*This pull request fixes issue #505, also support key as segment and add CORS header.*  
Complex type property now can be patched rightly.
=> fix issue 505 and add patch test cases, also support key as segment and add CORS header

src/GlobalSuppressions.cs
*This pull request is for CA warnings message cleanup -- CA13xx category (Globalization).*  
*Examine CA13xx warnings and remove if it is no longer applicable.*
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*
=> CA13xx(Globalization) warning message cleanup

src/Microsoft.Restier.AspNet/Query/RestierQueryBuilder.cs, src/Microsoft.Restier.Core/Extensions/TypeExtensions.cs, src/Microsoft.Restier.Core/Submit/ChangeSetItem.cs
This pull request fixes issue #578.
Entities with a `DateTime` property in their key can't be created/read/updated/deleted because OData Web API does not support `DateTime` in the keys. This pull request addresses this issue by converting `DateTimeOffset` to `DateTime` when necessary.
No additional work necessary.
=> Convert DateTimeOffset to DateTime when necessary

src/Microsoft.Restier.AspNet/Extensions/HttpConfigurationExtensions.cs, src/Microsoft.Restier.AspNet/Extensions/ServiceCollectionExtensions.cs, src/Microsoft.Restier.Core/Extensions/ServiceCollectionExtensions.cs, src/Microsoft.Restier.Core/RestierContainerBuilder.cs, src/Microsoft.Restier.Samples.Northwind.AspNet/App_Start/WebApiConfig.cs, src/Microsoft.Restier.Tests.Core/ConventionBasedMethodNameFactoryTests.cs, src/Microsoft.Restier.Tests.Core/InvocationContextTests.cs, src/Microsoft.Restier.Tests.Core/Model/DefaultModelHandlerTests.cs, src/Microsoft.Restier.Tests.Core/PropertyBagTests.cs
on the RestierContainerBuilder and added support for pre-odata and post-odata service registration hooks (as constructor arguments).
All unit tests pass.
=> Reverted to one ServicesCollection again

src/Microsoft.Restier.Tests.AspNet/FeatureTests/NavigationPropertyTests.cs
Modified NavigationPropertyTests to setup/teardown record state in the DbContext during execution.
#702
*This pull request fixes issue #702.*  
Added records to the context prior to execution to expose the desired test surface.  Removed these records after test run.
** none **
=> NavigationPropertyTest reliability improvement

src/Microsoft.Restier.AspNet/RestierController.cs, src/Microsoft.Restier.AspNetCore/RestierController.cs, src/Microsoft.Restier.Breakdance/RestierBreakdanceTestBase.cs, src/Microsoft.Restier.Core/Submit/ChangeSet.cs, src/Microsoft.Restier.Core/Submit/DefaultSubmitHandler.cs, src/Microsoft.Restier.Tests.AspNet/FeatureTests/BatchTests.cs, src/Microsoft.Restier.Tests.Core/ApiBaseTests.cs
*This pull request fixes issue #709.*  
Issue #1: Batch requests were failing for .NET Core because .NET Core requires the ODataBatch middleware to be registered (must be before UseMvc). It would be nice to do this automatically, but it wasn't clear where we would have access to the apibuilder in order to add the batch middleware. For now, I added the UseODataBatch to RestierBreakdanceTestBase, and developers using RESTier will have to add the same UseODataBatch in order to enable batch support in .NET Core.
Issue #2: In the JSON format, the content-type of batches within a response include odata.streaming=true in .NET Core, but not net472. Not sure why this difference, but both are valid so I just accounted for this in the tests. 
Issue #3: There were some threading issues with how we …
=> Fix Batch on .NET Core

src/Microsoft.Restier.AspNet/Filters/RestierExceptionFilterAttribute.cs, src/Microsoft.Restier.AspNet/RestierController.cs, src/Microsoft.Restier.AspNet/Routing/RestierRoutingConvention.cs, src/Microsoft.Restier.AspNetCore/Extensions/IApplicationBuilderExtensions.cs, src/Microsoft.Restier.AspNetCore/Filters/RestierExceptionFilterAttribute.cs, src/Microsoft.Restier.AspNetCore/RestierController.cs, src/Microsoft.Restier.AspNetCore/Routing/RestierRoutingConvention.cs, src/Microsoft.Restier.Samples.Northwind.AspNetCore/Startup.cs, src/Microsoft.Restier.Tests.AspNet/Baselines/StoreApi-ApiMetadata.txt, src/Microsoft.Restier.Tests.AspNet/FeatureTests/ActionTests.cs, src/Microsoft.Restier.Tests.AspNet/FeatureTests/FunctionTests.cs, src/Microsoft.Restier.Tests.AspNet/FeatureTests/MetadataTests.cs, src/Microsoft.Restier.Tests.AspNet/RestierControllerTests.cs, src/Microsoft.Restier.Tests.AspNetCore/Baselines/StoreApi-ApiMetadata.txt, src/Microsoft.Restier.Tests.AspNetCore/ClaimsPrincipalAccessorTests/ClaimsPrincipalAccessorTests.cs
-Adds support for falling back to OData conventions in .NET Core
-Fixes null ClaimsPrincipals.Current
-Fixes several test issues.
This pull request
1) adds code to RestierRoutingConvention in .NET Core to fall back to OData conventions.
2) renames UseThreadPrincipals to UseClaimsPrincipals and sets the ClaimsPrincipalSelector to return the current user
3) updates expected store-Api metadata baselines for tests
4) disables tests for filter segment, since that is not currently supported in webapi odata
5) Returns MethodNotAllowed for POST to a function
6) Returns BadRequest for missing required parameters
-Verify desired logic for UseClaimsPrincipals (perhaps rename) -- Does the updated code achieve what you had intended?
-Consider making fallback code for .net more similar to new logic …
=> Fix Remaining RESTier Issues

src/Microsoft.Restier.AspNet/Batch/RestierBatchChangeSetRequestItem.cs, src/Microsoft.Restier.AspNetCore/Batch/RestierBatchChangeSetRequestItem.cs
*This pull request fixes issue #760 
Concurrent dictionary to resolve the crashes.
Hopefully It won't have more concurrency errors. The default method doesn't resolve the requests all at the same time, and I don't believe it is tested properly after this change.
=> Batchhandler results in an error when doing bulk updates.

src/Microsoft.Restier.AspNetCore.Swagger/RestierSwaggerProvider.cs
When mapping a Restier route with a non empty route prefix, the generated swagger file does not include the route prefix in the `servers[0].url` property.
```csharp
app.MapRestier(restier => restier.MapApiRoute<EntityFrameworkApi<MyDbContext>>(routeName: "RestierDefault", routePrefix: "api"));
```
❌ The generated url is `http://localhost:5000`, making all requests from SwaggerUI fail with 404 errors.
The route prefix is included in the generated swagger file in the `servers[0].url` property.
✅ The generated url is `http://localhost:5000/api/`, making SwaggerUI usable.
Fixes #749
=> Observe the route prefix in RestierSwaggerProvider
