OData/RESTier

.gitignore
.nuget/NuGet.Config
src/Microsoft.Restier.EntityFramework/DbDomain.cs
src/Microsoft.Restier.EntityFramework7/Microsoft.Restier.EntityFramework7.csproj
src/Microsoft.Restier.EntityFramework7/Model/ModelProducer.cs
src/Microsoft.Restier.EntityFramework7/Submit/ChangeSetPreparer.cs
src/Microsoft.Restier.EntityFramework7/packages.config
src/Microsoft.Restier.Samples.Northwind.EF7/Microsoft.Restier.Samples.Northwind.EF7.csproj
src/Microsoft.Restier.Samples.Northwind.EF7/Web.config
src/Microsoft.Restier.Samples.Northwind.EF7/packages.config
src/Microsoft.Restier.Samples.Northwind/Models/NorthwindContext.cs
test/Microsoft.Restier.Samples.Northwind.EF7.Tests/App.config
test/Microsoft.Restier.Samples.Northwind.EF7.Tests/Microsoft.Restier.Samples.Northwind.EF7.Tests.csproj
test/Microsoft.Restier.Samples.Northwind.EF7.Tests/packages.config
test/Microsoft.Restier.Samples.Northwind.Tests/SaveTests.cs

Resolved comments in the original CR.
VS must have latest NuGet client tool to install EF7 packages.

Integrate EF7 beta6

---

src/Microsoft.Restier.EntityFramework/DbDomain.cs

Bug fix, CLSCompliant(false) should be only applied to EF7.

---

src/GlobalSuppressions.cs
src/Microsoft.Restier.WebApi/ODataDomainController.cs
src/Microsoft.Restier.WebApi/Properties/Resources.Designer.cs
src/Microsoft.Restier.WebApi/Properties/Resources.resx
test/Microsoft.Restier.WebApi.Test/ODataDomainControllerTests.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinE2ETestCases.cs

GitHub#115 should return 404 for non-existing entity

---

src/Microsoft.Restier.Core/Conventions/ConventionalChangeSetAuthorizer.cs
src/Microsoft.Restier.Core/Conventions/ConventionalChangeSetConstants.cs
src/Microsoft.Restier.Core/Conventions/ConventionalChangeSetEntryFilter.cs
src/Microsoft.Restier.Core/Conventions/ConventionalChangeSetEntryValidator.cs
src/Microsoft.Restier.Core/Conventions/ConventionalDomainModelBuilder.cs
src/Microsoft.Restier.Core/Conventions/ConventionalEntitySetFilter.cs
src/Microsoft.Restier.Core/Microsoft.Restier.Core.csproj
src/Microsoft.Restier.Core/Properties/Resources.Designer.cs
src/Microsoft.Restier.Core/Properties/Resources.resx
src/Microsoft.Restier.Core/Query/DefaultQueryExecutor.cs
src/Microsoft.Restier.Core/Query/QueryExpressionContext.cs
src/Microsoft.Restier.Core/QueryableSource.cs
src/Microsoft.Restier.Core/Submit/ChangeSetEntry.cs
src/Microsoft.Restier.EntityFramework/DbDomain.cs
src/Microsoft.Restier.EntityFramework/DbDomainConstants.cs
src/Microsoft.Restier.EntityFramework/Microsoft.Restier.EntityFramework.csproj
src/Microsoft.Restier.EntityFramework/Model/ModelProducer.cs
src/Microsoft.Restier.EntityFramework/Query/QueryExpressionSourcer.cs
src/Microsoft.Restier.EntityFramework/Submit/ChangeSetPreparer.cs
src/Microsoft.Restier.EntityFramework/Submit/SubmitExecutor.cs
src/Microsoft.Restier.Security/RoleBasedAuthorization.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/ODataDomainEntityTypeSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/ODataDomainFeedSerializer.cs
src/Microsoft.Restier.WebApi/ODataDomainController.cs
src/Microsoft.Restier.WebApi/ODataDomainFormattingAttribute.cs
src/Microsoft.Restier.WebApi/Properties/Resources.Designer.cs
src/Microsoft.Restier.WebApi/Properties/Resources.resx
src/Microsoft.Restier.WebApi/Routing/ODataDomainRoutingConvention.cs
src/Shared/EdmHelpers.cs
src/Shared/Ensure.cs

Clean up string literals in code

---

src/Microsoft.Restier.Samples.Northwind/Controllers/NorthwindController.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/DefaultODataDomainSerializerProvider.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/ODataDomainComplexTypeSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/ODataDomainFeedSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/ODataDomainPrimitiveSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/ODataDomainRawSerializer.cs
src/Microsoft.Restier.WebApi/Microsoft.Restier.WebApi.csproj
src/Microsoft.Restier.WebApi/ODataDomainController.cs
src/Microsoft.Restier.WebApi/ODataDomainPayloadValueConverter.cs
src/Microsoft.Restier.WebApi/Results/BaseCollectionResult.cs
src/Microsoft.Restier.WebApi/Results/BaseResult.cs
src/Microsoft.Restier.WebApi/Results/BaseSingleResult.cs
src/Microsoft.Restier.WebApi/Results/CollectionQueryResult.cs
src/Microsoft.Restier.WebApi/Results/ComplexResult.cs
src/Microsoft.Restier.WebApi/Results/EntityCollectionResult.cs
src/Microsoft.Restier.WebApi/Results/EntityResult.cs
src/Microsoft.Restier.WebApi/Results/ODataQueryResult.cs
src/Microsoft.Restier.WebApi/Results/PrimitiveResult.cs
src/Microsoft.Restier.WebApi/Results/RawResult.cs
src/Microsoft.Restier.WebApi/Results/SingleQueryResult.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/Microsoft.Restier.WebApi.Test.Scenario.csproj
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/PropertyAccessTests.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/UrlConventionsTests.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Controllers/TrippinController.cs

Not supported features: Enum and Collection<NonEntity>

Support property access in ODataDomainController

---

src/Microsoft.Restier.EntityFramework/Submit/ChangeSetPreparer.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/ServiceReference/TrippinProxy.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Models/Person.cs

Fix GitHub issue #269

---

src/Microsoft.Restier.EntityFramework/Query/QueryExecutor.cs
src/Microsoft.Restier.EntityFramework/Query/QueryExpressionSourcer.cs
src/Microsoft.Restier.EntityFramework/Submit/SubmitExecutor.cs
src/Microsoft.Restier.EntityFramework7/Model/ModelProducer.cs
src/Microsoft.Restier.EntityFramework7/Properties/AssemblyInfo.cs
src/Microsoft.Restier.EntityFramework7/Submit/ChangeSetPreparer.cs
src/Microsoft.Restier.Samples.Northwind/Models/NorthwindContext.cs

* Format text to meet FxCop requirements.
* Add cascade deletion configuration since EF7 has support now.
Verified that UTs passed for EF6.

EF7: Pass code analysis check. Cascade deletion support.

---

src/Microsoft.Restier.WebApi/Formatter/Serialization/DefaultRestierSerializerProvider.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierCollectionSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierComplexTypeSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierEntityTypeSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierEnumSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierFeedSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierPrimitiveSerializer.cs
src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierRawSerializer.cs
test/Microsoft.Restier.TestCommon/PublicApi.bsl

Make public all RESTier serializers

---

src/Microsoft.Restier.Core/ApiBase.cs
src/Microsoft.Restier.Core/ApiBuilderExtensions.cs
src/Microsoft.Restier.Core/ApiConfiguration.cs
src/Microsoft.Restier.Core/ApiContext.cs
src/Microsoft.Restier.Security/ApiConfigurationExtensions.cs
test/Microsoft.Restier.Core.Tests/Api.Tests.cs
test/Microsoft.Restier.Core.Tests/ApiBuilder.Tests.cs
test/Microsoft.Restier.Core.Tests/ApiConfiguration.Tests.cs
test/Microsoft.Restier.Core.Tests/ApiContext.Tests.cs
test/Microsoft.Restier.Core.Tests/InvocationContext.Tests.cs
test/Microsoft.Restier.TestCommon/PublicApi.bsl

Inner service instance injection. via public settable property.
Remove EnsureCommitted & IsCommitted.
Adds a remark section for the newly added ChianPrevious method.
Merge master branch.

Inner service instance injection.

---

src/Microsoft.Restier.Samples.Northwind/App_Start/WebApiConfig.cs
src/Microsoft.Restier.WebApi/HttpConfigurationExtensions.cs
src/Microsoft.Restier.WebApi/RestierPayloadValueConverter.cs
test/Microsoft.Restier.Samples.Northwind.Tests/OperationTests.cs
test/Microsoft.Restier.TestCommon/PublicApi.bsl
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/PropertyAccessTests.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Api/TrippinApi.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Microsoft.Restier.WebApi.Test.Services.Trippin.csproj
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Models/CustomizedPayloadValueConverter.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Web.config
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/packages.config

Fix #335 , user can register his own payload converter.

Utilize DI for payload converter

---

src/Microsoft.Restier.EntityFramework/Query/QueryExecutor.cs
src/Microsoft.Restier.EntityFramework7/Microsoft.Restier.EntityFramework7.csproj
src/Microsoft.Restier.EntityFramework7/Model/ModelProducer.cs
src/Microsoft.Restier.EntityFramework7/packages.config
test/Microsoft.Restier.EntityFramework7.Tests/Microsoft.Restier.EntityFramework7.Tests.csproj
test/Microsoft.Restier.EntityFramework7.Tests/packages.config
test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.EF7.Tests/Microsoft.Restier.Samples.Northwind.EF7.Tests.csproj
test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.EF7.Tests/packages.config
test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.EF7/Microsoft.Restier.Samples.Northwind.EF7.csproj
test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.EF7/Web.config
test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.EF7/packages.config
test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind/Models/NorthwindContext.cs

I'm too ignorant to find out that EF7 sqlserver package has been updated to RC1 months ago, with a new name. Sorry!

Update EF7 packages to RC1

---

RESTier.sln
src/GlobalSuppressions.cs
src/Microsoft.Restier.Core/Conventions/ConventionBasedEntitySetFilter.cs
src/Microsoft.Restier.Core/Query/IQueryExpressionFilter.cs
src/Microsoft.Restier.EntityFramework/DbApi.cs
src/Microsoft.Restier.EntityFramework/Microsoft.Restier.EntityFramework.csproj
src/Microsoft.Restier.EntityFramework/Query/QueryExpressionFilter.cs
src/Microsoft.Restier.WebApi/RestierQueryBuilder.cs
test/Microsoft.Restier.Core.Tests/Microsoft.Restier.Core.Tests.csproj
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinInMemoryE2ETest.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Microsoft.Restier.WebApi.Test.Services.Trippin.csproj
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/packages.config
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.TrippinInMemory/Microsoft.Restier.WebApi.Test.Services.TrippinInMemory.csproj
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.TrippinInMemory/Models/Person.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.TrippinInMemory/Models/Trip.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.TrippinInMemory/Models/TrippinApi.cs

Make when nav collection is null, In memory data source will return 200. part fix of issue #330

Make collection of navigation could be null for in-memory data source

---

src/Microsoft.Restier.WebApi/RestierController.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/Microsoft.Restier.WebApi.Test.Scenario.csproj
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinE2ETestCases.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/UrlConventionsTests.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/packages.config

Fix issue with $level Null reference exception

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Add More content to readme

---

src/Microsoft.Restier.EntityFramework/Submit/ChangeSetPreparer.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinE2ETestCases.cs

*This pull request fixes issue #363 .*  
If the current property value has null type, will get type information from model.

Fix issue when patch a property who has null value

---

test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.Tests/Baselines/TestCustomerKeyAsSegment.txt
test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.Tests/Microsoft.Restier.Samples.Northwind.Tests.csproj
test/ODataEndToEndTests/Microsoft.Restier.Samples.Northwind.Tests/ODataFeedTests.cs
test/Shared/ODataTestHelpers.cs

Support key as segment in RESTier with issue #160 
Add test case for key as segment
Need documents

Add test cases for key as segment

---

test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/ServiceReference/TrippinProxy.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinE2ETestCases.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Microsoft.Restier.WebApi.Test.Services.Trippin.csproj
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Models/Order.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Models/TrippinModel.cs

*This pull request fixes issue #341 .*  
Our code is already supported composite key, add test cases for composite key.

Support composite key

---

src/Microsoft.Restier.EntityFramework/Submit/ChangeSetPreparer.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinE2ETestCases.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Models/Person.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Services.Trippin/Models/Trip.cs

*This pull request fixes issue #380 .*  
Make put can work with key with type long(int64)

Fix issues when push entity whose key is long type

---

src/Microsoft.Restier.WebApi/Formatter/Serialization/RestierFeedSerializer.cs
test/ODataEndToEndTests/Microsoft.Restier.WebApi.Test.Scenario/TrippinE2ETestCases.cs

This pull request fixes issue #360.

Issue #360 Add basic support  in Restier

---

src/Microsoft.Restier.Core/Query/IQueryExpressionProcessor.cs
src/Microsoft.Restier.Core/Query/QueryExpressionContext.cs
src/Microsoft.Restier.Core/Query/QueryModelReference.cs
src/Microsoft.Restier.Core/Submit/ChangeSetItem.cs
src/Microsoft.Restier.Providers.EntityFramework/Submit/ChangeSetInitializer.cs
src/Microsoft.Restier.Publishers.OData/Extensions.cs
src/Microsoft.Restier.Publishers.OData/Query/RestierQueryBuilder.cs
src/Microsoft.Restier.Publishers.OData/RestierController.cs
src/Microsoft.Restier.Publishers.OData/Routing/RestierRoutingConvention.cs
test/Microsoft.Restier.Providers.EntityFramework.Tests/ChangeSetPreparerTests.cs
test/Microsoft.Restier.Publishers.OData.Test/RestierControllerTests.cs
test/Microsoft.Restier.TestCommon/PublicApi.bsl
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Northwind.Tests/SaveTests.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinE2EQueryTestCases.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinE2ETestCases.cs

Issues
This pull request fixes part of issue #117
Description
Add support of derived type patch/update/delete

Derivedtype support part 3

---

_posts/2016-04-23-02-05-Model-building-0-5-0.md
_posts/2016-04-24-02-08-Customize-Query.MD
_posts/2016-04-24-02-09-Customize-Submit.MD

*This pull request fixes issue #420.*  
Update some documents

Fix a error and update some names

---

src/GlobalSuppressions.cs
src/Microsoft.Restier.Core/Conventions/ConventionBasedChangeSetItemAuthorizer.cs
src/Microsoft.Restier.Core/Conventions/ConventionBasedOperationAuthorizer.cs
src/Microsoft.Restier.Core/Microsoft.Restier.Core.csproj
src/Microsoft.Restier.Core/Operation/IOperationAuthorizer.cs
src/Microsoft.Restier.Core/Operation/IOperationExecutor.cs
src/Microsoft.Restier.Core/Operation/OperationContext.cs
src/Microsoft.Restier.Core/ServiceCollectionExtensions.cs
src/Microsoft.Restier.Core/Submit/SubmitContext.cs
src/Microsoft.Restier.Publishers.OData/Filters/RestierExceptionFilterAttribute.cs
src/Microsoft.Restier.Publishers.OData/Formatter/Deserialization/DeserializationHelpers.cs
src/Microsoft.Restier.Publishers.OData/Microsoft.Restier.Publishers.OData.csproj
src/Microsoft.Restier.Publishers.OData/Operation/OperationExecutor.cs
src/Microsoft.Restier.Publishers.OData/Properties/Resources.Designer.cs
src/Microsoft.Restier.Publishers.OData/Properties/Resources.resx
src/Microsoft.Restier.Publishers.OData/Query/RestierQueryBuilder.cs
src/Microsoft.Restier.Publishers.OData/RestierController.cs
src/Microsoft.Restier.Publishers.OData/Routing/RestierRoutingConvention.cs
src/Microsoft.Restier.Publishers.OData/ServiceCollectionExtensions.cs
test/Microsoft.Restier.Publishers.OData.Test/RestierControllerTests.cs
test/Microsoft.Restier.TestCommon/PublicApi.bsl
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/E2ETestBase.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/UrlConventionsTests.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Api/TrippinApi.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Controllers/TrippinController.cs

*This pull request fixes issue #378 .*  
This is the second part, cover the action support without additional controller for operation
Document is needed to be updated.

Add action to be executed without additional controller.

---

src/GlobalSuppressions.cs
src/Microsoft.Restier.Providers.EntityFramework/Model/ModelProducer.cs
src/Microsoft.Restier.Publishers.OData/Microsoft.Restier.Publishers.OData.csproj
src/Microsoft.Restier.Publishers.OData/Model/ModelMapper.cs
src/Microsoft.Restier.Publishers.OData/Model/RestierModelBuilder.cs
src/Microsoft.Restier.Publishers.OData/ServiceCollectionExtensions.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinE2EQueryTestCases.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Api/TrippinApi.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Microsoft.OData.Service.Sample.Trippin.csproj
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Trippin/Models/PersonWithAge.cs

*This pull request fixes issue #460 .*  
Add imprative view with different entity type support
Need to update the document

Add imprative view with different entity type support

---

test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinInMemoryE2ETest.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/Api/TrippinApi.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/App_Start/WebApiConfig.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/Models/Person.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/Models/TripPinDataSource.cs

This pull request fix the TrippinInMemory failed test cases. 
- [   ] Test cases added

Fix Trippin In Memory Test Cases

---

src/Microsoft.Restier.Publishers.OData/Formatter/Serialization/RestierPrimitiveSerializer.cs
src/Microsoft.Restier.Publishers.OData/RestierPayloadValueConverter.cs

*This pull request fixes issue #488 *

upport datatime whose kind is Local

---

test/ODataEndToEnd/Microsoft.OData.Service.Sample.TrippinInMemory/App_Start/WebApiConfig.cs

*This pull request update the deployed sample service.*

add Filter etc to config after change to Restier 1.0.0 beta

---

test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/E2ETestBase.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinE2EQueryTestCases.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinE2ETestCases.cs
test/ODataEndToEnd/Microsoft.OData.Service.Sample.Tests/TrippinInMemoryE2ETest.cs

The automated build currently has 4 failed test cases:Fix TestPatchSuccessfully to wait for patch update before tesing patch result. (1 failed case)
Update DerivedTypeQuery* so that test names are unique. (3 failed cases)
- [   ] Test cases added

Fix failing test cases

---

README.md

*This pull request adds build badge for VSTS RESTier master branch rolling build.*  
*Add build badge for VSTS RESTier master branch rolling build.*
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

Add build badge for VSTS RESTier master branch rolling build.

---

src/Microsoft.Restier.Core/Microsoft.Restier.Core.nuspec
src/Microsoft.Restier.Providers.EntityFramework/Microsoft.Restier.Providers.EntityFramework.nuspec
src/Microsoft.Restier.Publishers.OData/Microsoft.Restier.Publishers.OData.nuspec
src/Microsoft.Restier/Microsoft.Restier.nuspec

*This pull request fixes issue of missing copyright information in nuspec.*  
*Add Microsoft copyright information.*
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

Updating CopyRight reference in nuspec file

---

src/Microsoft.Restier.Core/Microsoft.Restier.Core.nuspec
src/Microsoft.Restier.Providers.EntityFramework/Microsoft.Restier.Providers.EntityFramework.nuspec
src/Microsoft.Restier.Publishers.OData/Microsoft.Restier.Publishers.OData.nuspec
src/Microsoft.Restier/Microsoft.Restier.nuspec

Point Nuget package licenses to MIT license in RESTier repo.

Point Nuget package licenses to MIT license in RESTier repo.

---

src/Microsoft.Restier.AspNet/Microsoft.Restier.AspNet.csproj
src/Microsoft.Restier.Core/Microsoft.Restier.Core.csproj
src/Microsoft.Restier.EntityFramework/Microsoft.Restier.EntityFramework.csproj
src/Microsoft.Restier.Samples.Northwind.AspNet/Microsoft.Restier.Samples.Northwind.AspNet.csproj
src/Microsoft.Restier.Samples.Northwind.AspNet/Web.config
src/Microsoft.Restier.Tests.AspNet/Microsoft.Restier.Tests.AspNet.csproj
src/Microsoft.Restier.Tests.EntityFramework/Microsoft.Restier.Tests.EntityFramework.csproj
src/Microsoft.Restier.Tests.Shared/Microsoft.Restier.Tests.Shared.csproj

Update references to latest released OData libraries

Update references to latest libraries

---

src/Microsoft.Restier.AspNet/Extensions/HttpConfigurationExtensions.cs
src/Microsoft.Restier.AspNet/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.Restier.Core/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.Restier.EntityFramework/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.Restier.Samples.Northwind.AspNet/App_Start/WebApiConfig.cs
src/Microsoft.Restier.Tests.AspNet/ExceptionHandlerTests.cs
src/Microsoft.Restier.Tests.AspNet/FeatureTests/AuthorizationTests.cs
src/Microsoft.Restier.Tests.AspNet/Model/RestierModelExtenderTests.cs
src/Microsoft.Restier.Tests.AspNet/ODataControllerFallbackTests.cs
src/Microsoft.Restier.Tests.Core/Legacy/ApiBaseTests.cs
src/Microsoft.Restier.Tests.Core/Legacy/ConventionBasedMethodNameFactoryTests.cs
src/Microsoft.Restier.Tests.Core/Legacy/DefaultModelHandlerTests.cs
src/Microsoft.Restier.Tests.Core/Legacy/InvocationContextTests.cs
src/Microsoft.Restier.Tests.Core/ServiceCollectionExtensionTests.cs
src/Microsoft.Restier.Tests.Shared/Extensions/ServiceCollectionExtensions.cs

Part of https://github.com/OData/RESTier/pull/649
After a more thorough check of service registration I've got some more changes.
Cloudnimble needs to be updated.

More work on service configuration.

---

src/Microsoft.Restier.AspNet/Extensions/HttpConfigurationExtensions.cs

Fixes #657.
*This pull request fixes issue #657.
Creates an overload that accepts an HttpServer instance to facilitate Owin.

Overload for MapRestier.

---

src/Microsoft.Restier.Core/Query/PropertyModelReference.cs
src/Microsoft.Restier.Core/Query/QueryExpressionContext.cs
src/Microsoft.Restier.EntityFrameworkCore/Submit/EFChangeSetInitializer.cs
src/Microsoft.Restier.Samples.Northwind.AspNet/Microsoft.Restier.Samples.Northwind.AspNet.csproj
src/Microsoft.Restier.Tests.AspNet/FeatureTests/AuthorizationTests.cs
src/Microsoft.Restier.Tests.AspNet/FeatureTests/BatchTests.cs
src/Microsoft.Restier.Tests.AspNet/Microsoft.Restier.Tests.AspNet.csproj
src/Microsoft.Restier.Tests.AspNetCore/Microsoft.Restier.Tests.AspNetCore.csproj

-Fix filter on nav property
-Fix batch tests
*This pull request fixes filter on nav prop*  
*Briefly describe the changes of this pull request.*
- [ x ] *Test cases added*
- [ x ] *Build and test with one-click build and test script passed*

Fix filter on nav property

---

src/Microsoft.Restier.Tests.AspNet/FeatureTests/BatchTests.cs
src/Microsoft.Restier.Tests.AspNet/FeatureTests/NavigationPropertyTests.cs

*This pull request fixes issue adds a test to validate batch request/response payloads.*  
- [ x ] *Test cases added*
- [ x ] *Build and test with one-click build and test script passed*

Added test to validate batch request/response payloads

---

src/Microsoft.Restier.AspNetCore.Swagger/Extensions/IApplicationBuilderExtensions.cs
src/Microsoft.Restier.AspNetCore.Swagger/Extensions/IServiceCollectionExtensions.cs
src/Microsoft.Restier.AspNetCore.Swagger/Microsoft.Restier.AspNetCore.Swagger.csproj
src/Microsoft.Restier.AspNetCore.Swagger/RestierSwaggerProvider.cs
src/Microsoft.Restier.AspNetCore/Extensions/Restier_IEndpointRouteBuilderExtensions.cs
src/Microsoft.Restier.AspNetCore/Extensions/Restier_IRouteBuilderExtensions.cs
src/Microsoft.Restier.AspNetCore/Extensions/Restier_IServiceCollectionExtensions.cs
src/Microsoft.Restier.Core/Extensions/ApiBaseExtensions.cs
src/Microsoft.Restier.Core/Microsoft.Restier.Core.csproj
src/Microsoft.Restier.Core/Startup/RestierContainerBuilder.cs
src/Microsoft.Restier.Samples.Northwind.AspNetCore/Microsoft.Restier.Samples.Northwind.AspNetCore.csproj
src/Microsoft.Restier.Samples.Northwind.AspNetCore/Program.cs
src/Microsoft.Restier.Samples.Northwind.AspNetCore/Startup.cs
src/RESTier.sln

- Inject the RestierRouteBuilder so it can be accessed by the Swagger setup.
- Implement version of https://github.com/OData/RESTier/issues/720#issuecomment-1826147986
- Automagically configure OpenApi to handle the endpoints correctly.
Co-authored by @Tiberriver256.

Implementing Official Swagger Support

---

README.md
src/Microsoft.Restier.AspNetCore.Swagger/Extensions/IApplicationBuilderExtensions.cs
src/Microsoft.Restier.AspNetCore.Swagger/Extensions/IServiceCollectionExtensions.cs
src/Microsoft.Restier.AspNetCore.Swagger/Microsoft.Restier.AspNetCore.Swagger.csproj
src/Microsoft.Restier.AspNetCore.Swagger/README.md
src/Microsoft.Restier.AspNetCore.Swagger/RestierSwaggerProvider.cs
src/Microsoft.Restier.AspNetCore/Extensions/Restier_IEndpointRouteBuilderExtensions.cs
src/Microsoft.Restier.AspNetCore/Extensions/Restier_IRouteBuilderExtensions.cs
src/Microsoft.Restier.AspNetCore/Extensions/Restier_IServiceCollectionExtensions.cs
src/Microsoft.Restier.Core/Extensions/ApiBaseExtensions.cs
src/Microsoft.Restier.Core/Microsoft.Restier.Core.csproj
src/Microsoft.Restier.Core/Startup/RestierContainerBuilder.cs
src/Microsoft.Restier.Samples.Northwind.AspNetCore/Microsoft.Restier.Samples.Northwind.AspNetCore.csproj
src/Microsoft.Restier.Samples.Northwind.AspNetCore/Program.cs
src/Microsoft.Restier.Samples.Northwind.AspNetCore/Startup.cs
src/Microsoft.Restier.Tests.AspNetCore.Swagger/Extensions/IApplicationBuilderExtensionsTests.cs
src/Microsoft.Restier.Tests.AspNetCore.Swagger/Extensions/IServiceCollectionExtensionsTests.cs
src/Microsoft.Restier.Tests.AspNetCore.Swagger/Microsoft.Restier.Tests.AspNetCore.Swagger.csproj
src/RESTier.sln

Adding in Swagger support that I started after forking this branch for release.
Co-authored by @Tiberriver256).

Swagger Support for Restier 1.1 RTM
